/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StringsHelperFactory } from "./StringsHelperFactory";
export type { StringsHelper } from "./StringsHelper";
